### ISSUE TITLE
Wider Team Discussions

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#154]
- [ ] Need to present this to the wider team and get their feedback
- [x] One-on-one sessions/walkthroughs with specific members of DE/DM team.
- [x] Get feedback from DM/DEs once they've actually used it.

Probably want to run this in parallel with #26.

**Comment by canwaf** [comment]
Should this be reopened, @robons?

**Comment by robons** [comment]
> Should this be reopened, @robons?

I think most people came to the original talk tbh. It seems like everyone is moving over to the new csvcubed workflow without problem.

**Comment by canwaf** [comment]
Okay. So we're going to re-close it.
