### ISSUE TITLE
External User Documentation

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/csvcubed#192]
We should probably move to mkdocs/readthedocs for this.

Ross' rmarkdown stuff - https://gss-cogs.github.io/linked-data-book/

initial idea for the structure of the docs website:

- [x] Homepage - Landing page explaining what the project is and providing access to common links
- [x] Why
  - [x] Why would a user want to publish linked data @rossbowen
  - [x] Why in this format? 
- [x] Quickstart
  - [x] Installation - how to
  - [x] Shaping your data
     - [x] small discussion on single/multi measure cubes.
     - [x] link to #17 for more detailed discussion
  - [x] Creating a single-measure cube (from ingestion through to output)
  - [x] Creating a multi-measure cube (from ingestion through to output)
  - [x] Publishing your data - how to
     - [x] Tell them you can just upload all of the files into a directory on an HTTP web server.
- [ ] Guides - Tutorials/Walk-throughs to introduce different approaches to users
  - [x] Defining your catalog metadata - how, why and what you have to provide.
  - [x] What's the difference between a single-measure and multi-measure dataset? (#TBD)
  - [x] How to report a bug (#229)
  - [x] How to deal with missing observation values (#274)
  - [x] Errors - Documentation on what common errors mean and how to deal with it (#191)
  - [x] Getting the right shape of data (#17)
  - [x] How to define your columns' mappings (info.json v2)
    - [x] How to decide what the dimensions are versus what attributes are (#TBD)
    - [x] How to decide what the measure is versus what the unit is (#261)
  - [x] Publishing
    - [x] What the csvcubed outputs look like
       - [x] Discuss what the outputs look like and the fact that both the CSV + Metadata.json file need to be published together
       - [x] Touch on code-list CSV-Ws and make sure they publish them too.
       - [x] Which file should they link to?
    - [x] How to upload to PMD (via manual process currently) (#231)
- [x] Reference Metadata - Provides links to existing dimensions/code-lists/attributes+values/etc. which should be re-used
  - [x] Organisations (#230)
  - [x] Data Licenses (#230)
  - [x] Units of measure (QUDT) (#39)
  - [x] Dimensions
    - [x] Code-lists
  - [x] Attributes
    - [x] Attribute values
  - [x] Measures
- [x] Glossary (#259)
- [x] API Documentation

Need to have some kind of chat with Gareth about a suitable structure for the docs.
