### ISSUE TITLE
Local tool to preview metadata & data

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed#40]
Once users have generated their CSV-W, how do they verify that they've added all of the correct metadata and haven't missed something? Is there some kind of UI or report we can create to allow them browse what they've created without having to read a metadata JSON file?

`csvcubed inspect data-qube.csv-metadata.json`

Read the CSV-W using RDFLib and print out to console information such as
- [x] Oh btw this file is a data qube!
- [x] Metadata (including title, description, etc)
- [x] DSD (including column name, type (subtype i.e. literal attribute)
- [x] Codelists
- [ ] Head/tail of data in tabular format
- [ ] Value_counts on units+measures (i.e. similar to pandas value_counts))

`csvcubed inspect my-favourite-code-list.csv-metadata.json`

- [x] Oh btw this is a code-list
- [ ] You have X concepts
- [ ] You have a hierarchy depth of 1 (or 20)
- [ ] Here's the head/tail 10

Note:
* RDFlib can only access the metadata files as JSON-LD but cannot access the underlying observaitons, codelists values
* Pandas (or similar) will have to be used to access the contents of the various csv files created
