### ISSUE TITLE
SQlite Performance for Dataset Validation

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/csvcubed#466]
One of the things that fell out of spiking the use of pure python based ic validation is the challenge of performantly validating datasets of unknown sizes.

The purpose of this spike is to implement one or more of the simpler ic tests using a pure python approach: https://github.com/GSS-Cogs/gdp-sparql-tests/tree/master/tests/qb/qb-ics
I'd recommend ic 11 along with 15 and 16, though it's not set in stone.

**Tasks**

- [ ] Implemented using SQLlite **not** using pandas (even where you _could_ use pandas). We're investigating the advantage/drawbacks of using SQL queries as much as the performance.
- [ ] Use RDFlib exclusively for queries against the csvw data.
- [ ] Implement with a typical (i.e not large) dataset of the type we _tend_ to produce.
- [ ] Implement with 2-3 large outlier datasets (gb not mb).
- [ ] Include one extreme (10gb+) example, if need be auto generate to bulk up an existing csv.

Implement purely using SQLite + RDFlib, if we need a hybrid pandas/sqlite approach that'll be covered by the follow up ticket. We're investigating breakpoints/viability to inform design decisions here, not looking to build the final product.

**Acceptance Criteria**

- [ ] One or more python based ic implementations.
- [ ] Performance metrics for running the implemented ics against sample datasets of various sizes.

TODO: Consider whether we can just use [blaze](https://blaze.readthedocs.io/en/latest/quickstart.html#stored-data) as a drop-in replacement for pandas but have it backed by a sqlite (or other) database.

**Comment by robons** [comment]
Bad blaze doesn't work in 3.9+ https://github.com/blaze/blaze/issues/1689

**Comment by robons** [comment]
We discovered that pandas dataframes weren't the slowest bits of building the CSV-Ws. We've focused efforts elsewhere.
