### ISSUE TITLE
csvcubed "test" command

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/csvcubed#467]
Implement the initial "test" command for running pure python based ic validation.

example ic tests: https://github.com/GSS-Cogs/gdp-sparql-tests/tree/master/tests/qb/qb-ics (note: there are others, but these are the initial principle focus).

there is a spike into the use of SQLite as a mechanism for working with datasets of unknown sizes that should help inform this task: https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gss-cogs/csvcubed/466

there is an initial spike into this (don't use the code, the thinking has moved on a bit, but do check the conversation and Robs comments): https://github.com/GSS-Cogs/csvcubed/pull/396

**Tasks**

- [ ] Implement a "test" command for csvcubed.
- [ ] The test command should implement one or more ic tests using pure python.
- [ ] The tests must:
       1.)  Be performant (remember there are many of these to come, speed is paramount).
       2.) Scale, these must retain reasonable performance against very large datasets. 

**Acceptance Criteria**

A test command that calls one or more ic tests that execute performantly against datasets, even when large dataset sizes are used.

**Comment by mikeAdamss** [comment]
blocked by: https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gss-cogs/csvcubed/466
